#!/bin/bash
touch phonelistTemp.csv
touch phonelistTemp1.csv
sed 's/\([[:digit:]]\{3\}\)\([[:digit:]]\{3\}\)\([[:digit:]]\{4\}\)/(\1)\2-\3/g' ~/phonelist.csv > phonelistTemp1.csv 
sed 's/@[^,]*/@starhealth.org/' phonelistTemp1.csv > phonelistTemp.csv
mv phonelistTemp.csv ~/phonelist.csv
